---
- name: Setup ansible user, SSH keys, and sudo on all targets
  hosts: all
  become: yes
  vars:
    ansible_user_name: ansible

  tasks:

    - name: Ensure ansible user exists
      user:
        name: "{{ ansible_user_name }}"
        state: present
        shell: /bin/bash
        groups: sudo

    - name: Create .ssh directory for ansible user
      file:
        path: "/home/{{ ansible_user_name }}/.ssh"
        state: directory
        owner: "{{ ansible_user_name }}"
        group: "{{ ansible_user_name }}"
        mode: "0700"

    - name: Copy control node public key to authorized_keys
      authorized_key:
        user: "{{ ansible_user_name }}"
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_ed25519.pub') }}"
        path: "/home/{{ ansible_user_name }}/.ssh/authorized_keys"
        manage_dir: no

    - name: Set proper permissions for authorized_keys
      file:
        path: "/home/{{ ansible_user_name }}/.ssh/authorized_keys"
        owner: "{{ ansible_user_name }}"
        group: "{{ ansible_user_name }}"
        mode: "0600"

    - name: Add target hosts to known_hosts on control node
      known_hosts:
        name: "{{ ansible_host }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + ansible_host) }}"
        path: "/root/.ssh/known_hosts"

